model:
  target: unimumo.models.motion_vqvae_proprior.MotionVQVAE
  params:
    monitor: "val_loss"
    mean_dir: "/home/hanyang/code/fyp/fyp_project/data/peract/mean.npy"
    std_dir: "/home/hanyang/code/fyp/fyp_project/data/peract/std.npy"
    motion_mode: "proprior"  # "default" or "proprior"
    normalize_motion: True
    loss_config:
      target: unimumo.modules.loss.LossWithCrossEntropy
      params:
        lambda_commit: 0.02
        lambda_recon: 1.0
        gripper_weight: 0.01
    encoder_config:
      target: unimumo.modules.motion_vqvae_module.Encoder
      params:
        input_dim: 8
        output_dim: 24
        emb_dim_encoder: [ 8, 24 ]
        downsample: [ 1 ]
        dilation_growth_rate: 2
        depth_per_res_block: 1
        activation: 'relu'
    decoder_config:
      target: unimumo.modules.motion_vqvae_module.Decoder
      params:
        input_dim: 8
        output_dim: 24
        emb_dim_decoder: [ 24, 8 ]
        upsample: [ 1 ]
        dilation_growth_rate: 2
        depth_per_res_block: 1
        activation: 'relu'
    quantizer_config:
      dimension: 24
      n_q: 1
      q_dropout: False,
      bins: 128
    optimizer_config:
      optimizer:
        target: AdamW
        params:
          lr: 2e-4
          betas: [ 0.9, 0.99 ]
          weight_decay: 0.0
      lr_scheduler:
        target: CosineAnnealingLR
        params:
          T_max: 20000  # not sure about this
          eta_min: 1e-6


data:
  target: train.DataModuleFromConfig
  params:
    batch_size: 2
    wrap: True
    num_workers: 4
    train:
      target: unimumo.data.motion_vqvae_dataset.MotionVQVAEDataset
      params:
        split: "train"
        data_dir: "/home/hanyang/code/fyp/fyp_project/data/peract"
        preload_data: True
        load_observations: False
        chunk_size: 4
        n_chunk_per_traj: 4
        use_chunk: False
        load_proprioception: False
        load_sparce: True

    validation:
      target: unimumo.data.motion_vqvae_dataset.MotionVQVAEDataset
      params:
        split: "val"
        data_dir: "/home/hanyang/code/fyp/fyp_project/data/peract"
        preload_data: True
        load_observations: False
        chunk_size: 4
        n_chunk_per_traj: 4
        use_chunk: False
        load_proprioception: False
        load_sparce: True


lightning:
  callbacks:
    video_logger:
      target: unimumo.loggers_vqvae.TrajectoryLogger
      params:
        save_video: false
        num_videos: 1
        save_freq_epoch: 200
        rlb_config:
          data_path: "/home/hanyang/code/fyp/fyp_project/data/peract"
          image_size: "224,224"
          apply_rgb: True
          apply_pc: False

  trainer:
    benchmark: True
    devices: 1
    num_nodes: 1
    strategy: ddp
