model:
  target: unimumo.models.mgpt_vq.VQVae
  params:
    monitor: "val_loss"
    mean_std_dir: "/research/d2/fyp24/hyang2/fyp/code/3d_diffuser_actor/data/peract/raw"
    normalize_motion: True
    loss_config:
      target: unimumo.modules.loss.MotionVqVaeLoss
      params:
        lambda_commit: 0.02
        lambda_recon: 1.0
    encoder_decoder_config:
      input_emb_width: 8
      output_emb_width: 128
      down_t: 3
      stride_t: 2
      width: 128
      depth: 3
      dilation_growth_rate: 3
      norm: None
      activation: 'relu'
    quantizer_config:
      quantizer: "ema_reset"
      code_num: 512
      code_dim: 128
    optimizer_config:
      optimizer:
        target: AdamW
        params:
          lr: 2e-4
          betas: [ 0.9, 0.99 ]
          weight_decay: 0.0
      lr_scheduler:
        target: CosineAnnealingLR
        params:
          T_max: 1000  # not sure about this
          eta_min: 1e-6


data:
  target: train.DataModuleFromConfig
  params:
    batch_size: 32
    wrap: True
    num_workers: 4
    train:
      target: unimumo.data.motion_vqvae_dataset.MotionVQVAEDataset
      params:
        split: "train"
        data_dir: "/research/d2/fyp24/hyang2/fyp/code/3d_diffuser_actor/data/peract/raw"
        preload_data: False
        load_observations: False
        chunk_size: 4
        n_chunk_per_traj: 4

    validation:
      target: unimumo.data.motion_vqvae_dataset.MotionVQVAEDataset
      params:
        split: "val"
        data_dir: "/research/d2/fyp24/hyang2/fyp/code/3d_diffuser_actor/data/peract/raw"
        preload_data: False
        load_observations: False
        chunk_size: 4
        n_chunk_per_traj: 4


lightning:
  callbacks:
    video_logger:
      target: unimumo.loggers_vqvae.TrajectoryLogger
      params:
        save_video: True
        num_videos: 1
        save_freq_epoch: 10
        rlb_config:
          data_path: "/research/d2/fyp24/hyang2/fyp/code/3d_diffuser_actor/data/peract/raw"
          image_size: "256,256"
          apply_rgb: True
          apply_pc: True

  trainer:
    benchmark: True
    devices: 1
    num_nodes: 1
    strategy: ddp
